# Generated by Django 2.1.2 on 2019-03-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hect_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='img_url',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
