# Generated by Django 2.1.2 on 2019-03-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hect_app', '0002_text_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='user_name',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
